### ISSUE TITLE
使用table展示树形数据，右侧有固定列时，右侧固定列会出现展开箭头

### ISSUE THREAD

**Issue by 24955** [choerodon/choerodon-ui#111]
使用table展示树形数据，右侧有固定列时，右侧固定的列会出现展开箭头，并且该展开箭头点击时是可以展开树。反馈后，测试到的具体情况为 ，横线滚动条存在的情况会出现固定列有箭头出现
![image](https://user-images.githubusercontent.com/58674522/70402946-22c1b180-1a70-11ea-863b-ef3085f4e02c.png)
希望可以得到解决，谢谢

**Comment by Huihuawk** [comment]
> 使用table展示树形数据，右侧有固定列时，右侧固定的列会出现展开箭头，并且该展开箭头点击时是可以展开树。反馈后，测试到的具体情况为 ，横线滚动条存在的情况会出现固定列有箭头出现
> ![image](https://user-images.githubusercontent.com/58674522/70402946-22c1b180-1a70-11ea-863b-ef3085f4e02c.png)
> 希望可以得到解决，谢谢

0.8.46 已修复。
