### ISSUE TITLE
[Bug] DataSet-Children

### ISSUE THREAD

**Issue by Xeonice** [choerodon/choerodon-ui#113]
![image](https://user-images.githubusercontent.com/13403586/70525973-7c66d080-1b83-11ea-8a55-ea1a79a7950f.png)
![image](https://user-images.githubusercontent.com/13403586/70526042-a7512480-1b83-11ea-9dcf-f52c132564d2.png)
![image](https://user-images.githubusercontent.com/13403586/70526064-b3d57d00-1b83-11ea-8cc0-200722be94a6.png)
<br>
如上图所示，点击**新增列**时会对 `dataSet` 下的所有数据中 `childComponent` 新增一个对象，但是操作结束时，`console` 中打印出的第一条 `record` 未经过修改
版本：0.8.41
如何复现：请参考下图 `DataSet`
![image](https://user-images.githubusercontent.com/13403586/70526240-20e91280-1b84-11ea-9c70-8a0ce97900e6.png)
PS：删除该 `children` 定义后即可恢复正常
初步推测：`children` 在 `current`（默认第一条数据）绑定了 `dataSet`，导致第一条数据的修改只能从 `children` 指定的 `dataSet` 进行修改，而其他的数据则不受影响
期望结果：修改原始数据时，能够映射至 `children` 中的 `DataSet`

**Comment by HughHzWu** [comment]
请使用级联dataSet来新增数据， 还不是用record.set

**Comment by Xeonice** [comment]
> 请使用级联dataSet来新增数据， 还不是用record.set

@HughHzWu 级联 DataSet 初始化时只读入了 current 绑定的数据，get 可以通过 getCascadeRecord，但是如何 set 其余 Record 下的数据？

**Comment by HughHzWu** [comment]
> > 请使用级联dataSet来新增数据， 还不是用record.set
> 
> @HughHzWu 级联 DataSet 初始化时只读入了 current 绑定的数据，get 可以通过 getCascadeRecord，但是如何 set 其余 Record 下的数据？

可以通过record.getCascadeRecords(childName)获得 级联的record数组，再定位到某条record进行set数据

**Comment by HughHzWu** [comment]
> ![image](https://user-images.githubusercontent.com/13403586/70525973-7c66d080-1b83-11ea-8a55-ea1a79a7950f.png)
> ![image](https://user-images.githubusercontent.com/13403586/70526042-a7512480-1b83-11ea-9dcf-f52c132564d2.png)
> ![image](https://user-images.githubusercontent.com/13403586/70526064-b3d57d00-1b83-11ea-8cc0-200722be94a6.png)
> 
> 
> 如上图所示，点击**新增列**时会对 `dataSet` 下的所有数据中 `childComponent` 新增一个对象，但是操作结束时，`console` 中打印出的第一条 `record` 未经过修改
> 版本：0.8.41
> 如何复现：请参考下图 `DataSet`
> ![image](https://user-images.githubusercontent.com/13403586/70526240-20e91280-1b84-11ea-9c70-8a0ce97900e6.png)
> PS：删除该 `children` 定义后即可恢复正常
> 初步推测：`children` 在 `current`（默认第一条数据）绑定了 `dataSet`，导致第一条数据的修改只能从 `children` 指定的 `dataSet` 进行修改，而其他的数据则不受影响
> 期望结果：修改原始数据时，能够映射至 `children` 中的 `DataSet`

你这个数据结构是有问题的，组件之间应该用树状结构来维护，还不是用级联来维护。
