### ISSUE TITLE
[Bug]Icon component class

### ISSUE THREAD

**Issue by konnga** [choerodon/choerodon-ui#114]
choerodon-ui 组件的 class 都带有 c7n 前缀，但是 Icon 组件渲染出来后没有 c7n 前缀，导致使用自定义图标资源，比如iconfont会出现图标覆盖。

![1D485BA35E0DAE6E4685DFC92899F376](https://user-images.githubusercontent.com/18214609/70586092-29336300-1c01-11ea-9fd6-5e74d4a5360b.jpg)

使用了iconfont之后，如果存在同名的class，就好出现c7n图标不显示

![C8341A5CBD103CA3A90010345100913C](https://user-images.githubusercontent.com/18214609/70586268-91824480-1c01-11ea-8bfb-abed3d44b83d.jpg)

![9921575884211_ pic_hd](https://user-images.githubusercontent.com/18214609/70586286-9f37ca00-1c01-11ea-9d96-cdb172ab984d.jpg)

![9931575884211_ pic_hd](https://user-images.githubusercontent.com/18214609/70586304-a8289b80-1c01-11ea-81b0-d58e58b56dea.jpg)

**Comment by Huihuawk** [comment]
下个版本 c7n icon 前缀默认改成 c7n-icon
iconfontPrefix 全局配置需要配合 less预变量 iconfont-css-prefix 一起修改。
