### ISSUE TITLE
c7n的Pagination组件样式和hzero的分页组件样式不统一

### ISSUE THREAD

**Issue by houmao** [choerodon/choerodon-ui#123]
在一个系统中分页出现两种样式，平台级别的页面用的是hzero-ui，而目前开发要求用c7n，两种不同的分页样式.....
![image](https://user-images.githubusercontent.com/20122487/71607307-1e8e3d00-2bb3-11ea-81aa-0cdd8a8c9463.png)
![image](https://user-images.githubusercontent.com/20122487/71607316-2cdc5900-2bb3-11ea-8c61-767483378f75.png)

**Comment by Huihuawk** [comment]
> 在一个系统中分页出现两种样式，平台级别的页面用的是hzero-ui，而目前开发要求用c7n，两种不同的分页样式.....
> ![image](https://user-images.githubusercontent.com/20122487/71607307-1e8e3d00-2bb3-11ea-81aa-0cdd8a8c9463.png)
> ![image](https://user-images.githubusercontent.com/20122487/71607316-2cdc5900-2bb3-11ea-8c61-767483378f75.png)

https://choerodon.github.io/choerodon-ui/components-pro/pagination-cn/
有相关属性可配置
