### ISSUE TITLE
请问下猪齿鱼UI基于Ant Design@3.4.0的，后续有升级Ant Design的版本吗？

### ISSUE THREAD

**Issue by xiaokaiwangcc** [choerodon/choerodon-ui#134]
基于 Ant Design@3.4.0 的 Choerodon UI 的 React 实现，后续Ant Design的版本有升级吗 ？

**Comment by Huihuawk** [comment]
基于其实现，后续修改、更新、迭代都是猪齿鱼本身了，和antd没关系了
