### ISSUE TITLE
和antd有什么关系？

### ISSUE THREAD

**Issue by dzjwan521** [choerodon/choerodon-ui#16]
这个和antd关系是什么  很多链接点过去都是antd

**Comment by xuhailin** [comment]
基于antd 开发的。
你可以访问猪齿鱼的[官网](http://choerodon.io)查看 Choerodon UI 的文档

**Comment by Tangpriest** [comment]
满足了 我们想用antd 的中文文档 又想用material ui 的设计的需求

**Comment by HughHzWu** [comment]
choerodon-ui文档地址http://ui.choerodon.io/docs/react/introduce-cn
