### ISSUE TITLE
dataset field设置为“currency”类型时，无法指定币种精度

### ISSUE THREAD

**Issue by twtyjvkg** [choerodon/choerodon-ui#181]
业务场景：在选择支付币种时，会带出精度字段，付款金额需要根据精度字段显示对应的精度。

目前currency类型好像只会显示两位小数，建议后期能加个精度属性，这样就不用自定义editor去实现这个业务场景了

**Comment by Huihuawk** [comment]
https://codepen.io/huihuawk/pen/VwvbdRZ
你好，可以参考这个demo,后续会同步加在官网示例中。

**Comment by twtyjvkg** [comment]
可以考虑加到field里去吗，这样就不用每个编辑器都写render了

**Comment by twtyjvkg** [comment]
可以考虑加到dataset的field里去吗，这样就不用每个编辑器都写renderer了

**Comment by twtyjvkg** [comment]
可以考虑加到dataset的field里去吗，这样就不用每个编辑器都写renderer了
