### ISSUE TITLE
datePicker指定最大值、最小值的问题

### ISSUE THREAD

**Issue by twtyjvkg** [choerodon/choerodon-ui#192]
```typescript
 {
        name: 'reportDateFrom',
        type: FieldType.date,
        max: 'reportDateTo',
        label: intl.get('hssp.screen.exp_report_header.report_date_from'),
      },
      {
        name: 'reportDateTo',
        type: FieldType.date,
        min: 'reportDateFrom',
        label: intl.get('hssp.screen.exp_report_header.report_date_to'),
      },
```
在dataset的fields里给日期字段指定了最大值、最小值之后，在没有选择日期时，最大值、最小值都会变成当前日期。
这样会导致用户`日期从`选不到当前日期之后的日期，`日期到`选不到当前日期之前的日期。如果选了之后再清空，就全部变成不可选了。
![image](https://user-images.githubusercontent.com/26063786/81375774-d076e080-9134-11ea-9d0c-7eb1606b0e4e.png)

![image](https://user-images.githubusercontent.com/26063786/81375814-e1275680-9134-11ea-99d5-d02c14b0e3f9.png)

能否改成没有值的时候不做限制？

**Comment by Huihuawk** [comment]
已修复，会在下个版本可用。
