### ISSUE TITLE
无法自定义表单组件的只读样式

### ISSUE THREAD

**Issue by twtyjvkg** [choerodon/choerodon-ui#203]
能否像必输的`c7n-pro-field-required`样式类一样，给只读组件添加一个`c7n-pro-field-readonly`的样式类？
因为现在`Select`之类的组件，里面的`input`标签始终是readonly的，所以没有办法通过`readonly`属性自定义只读的样式。

**Comment by Huihuawk** [comment]
组件库目前不会加，可以自行判断加自定义类名。
