### ISSUE TITLE
如何 快速开始 一个项目？

### ISSUE THREAD

**Issue by zt1820057934** [choerodon/choerodon-ui#238]
我是一个后端， 对前端了解不多， 看到猪齿鱼这个UI风格很棒， 但如何快速的构造一个完整(带路由、权限等)、简易、UI风格
统一的项目， 供后续开发？ 通过提供的帮助文档我只能零星的知道其中的某个组件怎么用。 找一个现成的react项目，替换掉全部
的component ?  antd pro 则提供了一键初始化项目的功能。 

这个要求是不是太大了？😂

**Comment by Huihuawk** [comment]
你好，非常感谢您对我们UI库的关注。
简单的 react 前端项目使用我们UI库，可使用cra 快速开始：https://choerodon.gitee.io/choerodon-ui/zh/docs/other/use-with-create-react-app。也可在线尝试我们的 Pro 组件，极大提高开发效率。
类似 antd pro 脚手架创建一套完整(带路由、权限等)的项目我们也是有的，预计在7月底或8月开源，可以期待一下，内附功能强大，已有多个成熟项目使用并发布。本月也有相关开放文档平台供大家持续关注。开放后会再联系您。谢谢

**Comment by zt1820057934** [comment]
期待~  👍 👍 👍
