### ISSUE TITLE
Upload 组件 如何显示dataSet 中查询出的地址所在图片

### ISSUE THREAD

**Issue by zt1820057934** [choerodon/choerodon-ui#251]
<img width="602" alt="截屏2020-08-05 下午5 47 34" src="https://user-images.githubusercontent.com/31762662/89398476-c1a7c600-d743-11ea-9a3f-6962af321399.png">
<img width="563" alt="截屏2020-08-05 下午5 50 52" src="https://user-images.githubusercontent.com/31762662/89398847-37ac2d00-d744-11ea-8d11-65fe7c0585b8.png">

请问， 我定义一个dataSet， 绑定在一个form中， avatarUrl是后端查询得到一个图片地址， 怎么让表单中的Upload默认展示出这个地址的图片。
组件上是说props 可以 放入一个fileList， 但我不知如何从dataSet中获取到图片地址
`
const avatarField = currentDataSet.getField('avatarUrl') 
`
`
const value = avatarField.getValue() //  ->  undefined,  得到form时还未开始查询,    先currentDataSet.query()一下 又有错误
`

**Comment by Huihuawk** [comment]
你好，可以参考这个demo. https://codesandbox.io/s/wizardly-haibt-ux4rq
如果需要和ds再关联，可以在upload相关回调函数内 使用 ds.current.set('avatarUrl', xxxx) 来更新ds中对应avatarUrl的值。

**Comment by zt1820057934** [comment]
谢谢， 这个依然是 写死的吧，不是用ds查出来的 
<img width="485" alt="截屏2020-08-05 下午6 27 09" src="https://user-images.githubusercontent.com/31762662/89402357-4b0dc700-d749-11ea-91da-84f83298dc47.png">
是在这把地址保存下， 放进fileList中吗？ 我们用的hooks, dataSet 和 视图 不在一起， 也可以用传过去吗?

**Comment by Huihuawk** [comment]
这个不影响的，你要展示的信息是 ds查出来的，那在视图那里可从查询到的 record中取了avatarUrl放进fileList即可（在合适的生命周期处理）。

**Comment by zt1820057934** [comment]
哦哦， 好， 我试下吧， 😂
