### ISSUE TITLE
Modal 弹出框Upload组件不是最新

### ISSUE THREAD

**Issue by zt1820057934** [choerodon/choerodon-ui#259]
[ISSUE-256](https://github.com/choerodon/choerodon-ui/issues/256)

这个问题依然 还没解决啊， 下面的API props什么的看不太懂， 
```
const modal = Modal.open(...)
我把modal 传进 loadData 函数那， setState完了后， 不管我 
modal.render()/ renderChildren(modal.getBody())/ forceUpdate/ renderChildren( getForm(dataSet) )  。。  
都不行啊   控制台显示 renderChildren 不是一个function
```
Form绑定dataSet， 查询虽然是异步， 但都正常显示了， 就头像这 查询时放进state里， filelist查state， 不是最新的

**Comment by Huihuawk** [comment]
你好，最近有点忙，相关前端使用方面问题可能需要你自己多尝试一下了，有更多问题可以在这个开源论坛里面提问，https://forum.choerodon.io/，或者邮箱联系我们
我们的开源也开源了一部分了，后续这个论坛也会整合起来，感谢您的关注。
