### ISSUE TITLE
请问下table组件行和列的合并单元格有提供方法吗

### ISSUE THREAD

**Issue by CMemorY180819** [choerodon/choerodon-ui#43]
如题

**Comment by CMemorY180819** [comment]
列标题的看到官方手册有提供，那行标题是否有提供(实际业务中包含一些固定格式的表样，假设第一列作为行标题的话，怎么实现第一列纵向的合并单元格)

**Comment by wmzzh117** [comment]
https://choerodon.github.io/choerodon-ui/components/table-cn/

**Comment by CMemorY180819** [comment]
> https://choerodon.github.io/choerodon-ui/components/table-cn/

Pretty good~
