### ISSUE TITLE
c7n的Lov组件在不改变值集视图显示值的情况下，想显示Code

### ISSUE THREAD

**Issue by 20235** [choerodon/choerodon-ui#98]
值集视图可能会用于很多个页面 而大多数需要显示的是name，偶尔有两个地方需要显示code，所以希望c7n针对这种情况，优化一下Lov组件，新增属性用于修改显示值即可

**Comment by 20235** [comment]
版本： 0.8.37
react中使用

**Comment by HughHzWu** [comment]
0.8.39已改善该问题，Field上设置textField优先级高于Lov配置的textField
